# Catalogue Management Service Restful APIs
info:
  app:
    name: Spring Sample Application
    description: This is my first spring boot application
    version: 1.0.0

# Spring boot actuator configurations
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics

# Configure Logging
logging:
  level:
    root: ERROR
    com.toomuch2learn: DEBUG
    org.springframework.web: ERROR
    org.hibernate: ERROR
    com.zaxxer.hikari: ERROR
    org.apache.catalina: ERROR

# Configure Spring specific properties
spring:

  # Enable/Disable hot swapping
  devtools:
    restart:
      enabled: true
      log-condition-evaluation-delta: false

  # If there is no handler found for the request path, then throw error
  mvc:
    throw-exception-if-no-handler-found: true

  # multipart properties for file uploads
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  # Properties for configuring jackson mapper
  jackson:
    mapper:
      # For enums, consider case insensitive when parsing to json object
      accept-case-insensitive-enums: true

  resources:
    add-mappings: false

  # Datasource Configurations
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/cataloguedb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

# Custom Configurations
file:
  upload-location: E:\Projects\2much2learn\2much2learn_examples\catalogue-crud